In [1]:
import pandas as pd

In [2]:
df_main = pd.read_csv('vaccinations.csv')
df_main

             location        date             vaccine  total_vaccinations
0           Argentina  2020-12-29             Moderna                   2
1           Argentina  2020-12-29  Oxford/AstraZeneca                   3
2           Argentina  2020-12-29   Sinopharm/Beijing                   1
3           Argentina  2020-12-29           Sputnik V               20481
4           Argentina  2020-12-30             Moderna                   2
...               ...         ...                 ...                 ...
35618  European Union  2022-03-29  Oxford/AstraZeneca            67403106
35619  European Union  2022-03-29     Pfizer/BioNTech           600519998
35620  European Union  2022-03-29   Sinopharm/Beijing             2301516
35621  European Union  2022-03-29             Sinovac                1809
35622  European Union  2022-03-29           Sputnik V             1845103

[35623 rows x 4 columns]

In [3]:
df_main['vaccine'].unique()

array(['Moderna', 'Oxford/AstraZeneca', 'Sinopharm/Beijing', 'Sputnik V',
       'CanSino', 'Pfizer/BioNTech', 'Johnson&Johnson', 'Novavax',
       'Sinovac', 'Covaxin'], dtype=object)

In [8]:
df_vaccines = df_main.groupby('vaccine')['total_vaccinations'].sum().reset_index()
df_vaccines = df_vaccines.sort_values('total_vaccinations', ascending=False)
df_vaccines = df_vaccines.reset_index(drop=True)
df_vaccines

              vaccine  total_vaccinations
0     Pfizer/BioNTech        344835955037
1             Moderna        103072147621
2  Oxford/AstraZeneca         46451509497
3             Sinovac         13407163275
4     Johnson&Johnson         12611375881
5   Sinopharm/Beijing         10877006517
6           Sputnik V          5787343199
7             CanSino           271397675
8             Novavax             8268113
9             Covaxin                3572

In [11]:
df_vaccines.to_csv('vaccination_numbers.csv', index= False)

In [16]:
df_main['date'][0]

'2020-12-29'

In [29]:
def find_num(y, m):
    if y == 2020:
        return 1
    elif y == 2021:
        return  m + 1
    else:
        return m + 13

In [39]:
import pandas as pd
df_main['year'] = pd.to_datetime(df_main['date']).dt.year # create a new column for year
df_main['month'] = pd.to_datetime(df_main['date']).dt.month # create a new column for month
df_main['number'] = df_main.apply(lambda row: find_num(row['year'], row['month']), axis=1)
vaccine_trends = df_main.groupby(['vaccine', 'year', 'month', 'number'])['total_vaccinations'].sum().reset_index().sort_values(['number','vaccine'])

In [42]:
vaccine_trends[vaccine_trends.vaccine == 'Pfizer/BioNTech'].to_csv('Pfizer.csv', index = False)

In [43]:
vaccine_trends[vaccine_trends.vaccine == 'Moderna'].to_csv('Moderna.csv', index = False)

In [44]:
vaccine_trends[vaccine_trends.vaccine == 'Oxford/AstraZeneca'].to_csv('AstraZeneca.csv', index = False)

In [45]:
df_main['location'].unique()

array(['Argentina', 'Austria', 'Belgium', 'Bulgaria', 'Chile', 'Croatia',
       'Cyprus', 'Czechia', 'Denmark', 'Ecuador', 'Estonia', 'Finland',
       'France', 'Germany', 'Hong Kong', 'Hungary', 'Iceland', 'Ireland',
       'Italy', 'Japan', 'Latvia', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Malta', 'Nepal', 'Netherlands', 'Norway', 'Peru',
       'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia',
       'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland',
       'Ukraine', 'United States', 'Uruguay', 'European Union'],
      dtype=object)

In [48]:
countries = pd.read_csv('countries.csv')
countries

            Country  Deaths/1M pop
0       Afghanistan          195.0
1           Albania         1257.0
2           Algeria          152.0
3           Andorra         2130.0
4            Angola           55.0
..              ...            ...
226  Western Sahara            2.0
227           World          886.0
228           Yemen           69.0
229          Zambia          209.0
230        Zimbabwe          373.0

[231 rows x 2 columns]

In [63]:
df_combined = df_main.groupby(['location', 'vaccine'])['total_vaccinations'].sum().reset_index()

In [64]:
df_combined

          location             vaccine  total_vaccinations
0        Argentina             CanSino            53950431
1        Argentina             Moderna           893386753
2        Argentina  Oxford/AstraZeneca          5618580845
3        Argentina     Pfizer/BioNTech          1307660776
4        Argentina   Sinopharm/Beijing          5713239160
..             ...                 ...                 ...
189  United States             Moderna         55294886137
190  United States     Pfizer/BioNTech         79776473000
191        Uruguay  Oxford/AstraZeneca            27243328
192        Uruguay     Pfizer/BioNTech           589726730
193        Uruguay             Sinovac          1047602618

[194 rows x 3 columns]

In [67]:
df_combined["vaccine"].unique()

array(['CanSino', 'Moderna', 'Oxford/AstraZeneca', 'Pfizer/BioNTech',
       'Sinopharm/Beijing', 'Sputnik V', 'Johnson&Johnson', 'Novavax',
       'Sinovac', 'Covaxin'], dtype=object)

In [65]:
df_combined.to_csv('country_numbers.csv', index=False)

In [54]:
df_combined= df_combined.pivot(index='location', columns='vaccine', values='total_vaccinations')
df_combined.to_csv('flattened_file.csv') # save the flattened file
df_combined = pd.read_csv('flattened_file.csv')
df_combined

,location,CanSino,Covaxin,Johnson&Johnson,Moderna,Novavax,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,Sinovac,Sputnik V
0,Argentina,53950431.0,NaN,NaN,8.933868e+08,NaN,5.618581e+09,1.307661e+09,5.713239e+09,NaN,5.092133e+09
1,Austria,NaN,NaN,1.263894e+07,5.436887e+07,11819.0,7.372778e+07,4.557673e+08,NaN,NaN,NaN
2,Belgium,NaN,NaN,1.621113e+07,9.354474e+07,107.0,1.256663e+08,5.989736e+08,NaN,NaN,NaN
3,Bulgaria,NaN,NaN,1.198064e+07,1.560478e+07,NaN,2.352012e+07,8.313276e+07,NaN,NaN,NaN
4,Chile,153505458.0,NaN,NaN,NaN,NaN,1.513017e+08,2.205676e+09,NaN,7.421275e+09,NaN
5,Croatia,NaN,NaN,5.382836e+06,1.783213e+07,479.0,2.639237e+07,1.308606e+08,NaN,NaN,NaN
6,Cyprus,NaN,NaN,9.168150e+05,4.782633e+06,59.0,1.139933e+07,3.796457e+07,NaN,NaN,NaN
7,Czechia,NaN,NaN,8.293091e+07,3.552392e+08,41996.0,2.252249e+08,3.441540e+09,NaN,NaN,NaN
8,Denmark,NaN,NaN,1.947563e+06,5.252257e+07,NaN,8.301687e+06,3.475988e+08,NaN,NaN,NaN
9,Ecuador,63941786.0,NaN,NaN,NaN,NaN,5.740528e+08,1.399258e+09,NaN,2.561852e+09,NaN
10,Estonia,NaN,NaN,2.382223e+06,7.100996e+06,207.0,1.151180e+07,4.942954e+07,NaN,NaN,NaN
11,European Union,NaN,3506.0,4.519774e+09,2.439189e+10,2066859.0,2.170061e+10,1.410337e+11,7.438711e+08,5.175290e+05,6.277489e+08
12,Finland,NaN,NaN,0.000000e+00,4.801806e+07,NaN,2.676701e+07,2.991248e+08,NaN,NaN,NaN
13,France,NaN,NaN,2.978426e+08,4.074001e+09,NaN,2.579872e+09,2.522532e+10,NaN,NaN,NaN
14,Germany,NaN,NaN,9.205289e+08,4.719170e+09,1348545.0,4.188139e+09,2.915364e+10,NaN,NaN,NaN
15,Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,1.643527e+09,NaN,1.041142e+09,NaN
16,Hungary,NaN,NaN,9.331140e+06,3.786128e+07,NaN,5.847525e+07,3.139785e+08,1.045858e+08,NaN,6.708046e+07
17,Iceland,NaN,NaN,4.913000e+03,3.548400e+05,NaN,7.200000e+01,4.200838e+06,NaN,NaN,NaN
18,Ireland,NaN,NaN,8.756933e+06,3.216439e+07,NaN,4.431227e+07,2.610461e+08,NaN,NaN,NaN
19,Italy,NaN,NaN,4.220771e+08,4.925954e+09,507902.0,2.425777e+09,2.053227e+10,NaN,NaN,NaN
20,Japan,NaN,NaN,NaN,1.415208e+08,NaN,NaN,3.768902e+09,NaN,NaN,NaN
21,Latvia,NaN,NaN,5.726386e+07,1.244435e+08,2189.0,6.160848e+07,3.528115e+08,3.560000e+02,3.800000e+01,NaN
22,Liechtenstein,NaN,NaN,4.646000e+03,1.543114e+06,NaN,NaN,7.512990e+05,NaN,NaN,NaN
23,Lithuania,NaN,NaN,8.440297e+06,1.224147e+07,NaN,2.402843e+07,1.097743e+08,NaN,NaN,NaN
24,Luxembourg,NaN,NaN,1.596563e+06,5.942258e+06,532.0,4.841859e+06,2.516063e+07,NaN,NaN,NaN
25,Malta,NaN,NaN,1.202381e+06,4.502141e+06,NaN,1.063862e+07,2.624406e+07,NaN,NaN,NaN
26,Nepal,NaN,NaN,1.118813e+08,1.812575e+08,NaN,3.530906e+08,1.984490e+07,6.771564e+08,NaN,NaN
27,Netherlands,NaN,NaN,3.404599e+07,1.347043e+08,323.0,1.297025e+08,8.180842e+08,NaN,NaN,NaN
28,Norway,NaN,NaN,2.614750e+05,6.222832e+07,NaN,8.044875e+06,2.860577e+08,NaN,NaN,NaN
29,Peru,NaN,NaN,NaN,NaN,NaN,7.241190e+08,6.157883e+09,3.638123e+09,NaN,NaN
30,Poland,NaN,NaN,8.837319e+07,1.480395e+08,11067.0,2.452178e+08,1.342429e+09,NaN,NaN,NaN
31,Portugal,NaN,66.0,3.906225e+07,9.117436e+07,0.0,9.593523e+07,4.756099e+08,3.048300e+04,6.502200e+04,NaN
32,Romania,NaN,NaN,3.737618e+08,2.846886e+08,NaN,2.030900e+08,3.290245e+09,NaN,NaN,NaN
33,Slovakia,NaN,NaN,4.577868e+06,2.406459e+07,660.0,2.319607e+07,1.717788e+08,NaN,NaN,3.805440e+05
34,Slovenia,NaN,NaN,4.084514e+06,9.077059e+06,51.0,1.354594e+07,7.256522e+07,NaN,NaN,NaN
35,South Africa,NaN,NaN,2.005567e+08,NaN,NaN,NaN,6.203154e+08,NaN,NaN,NaN
36,South Korea,NaN,NaN,4.108059e+08,3.442773e+09,4275195.0,5.415624e+09,1.251304e+10,NaN,NaN,NaN
37,Spain,NaN,NaN,7.824416e+07,5.084171e+08,NaN,4.316192e+08,2.244537e+09,NaN,NaN,NaN
38,Sweden,NaN,NaN,NaN,8.586669e+07,123.0,6.119736e+07,4.820933e+08,NaN,NaN,NaN
39,Switzerland,NaN,NaN,7.809174e+06,2.327226e+09,NaN,NaN,1.356914e+09,NaN,NaN,NaN
40,Ukraine,NaN,NaN,3.987506e+06,4.637534e+08,NaN,7.451318e+08,1.810085e+09,NaN,1.334709e+09,NaN
41,United States,NaN,NaN,4.872710e+09,5.529489e+10,NaN,NaN,7.977647e+10,NaN,NaN,NaN
42,Uruguay,NaN,NaN,NaN,NaN,NaN,2.724333e+07,5.897267e+08,NaN,1.047603e+09,NaN

In [55]:
final_combined = df_combined.merge(countries, left_on= 'location', right_on='Country')
final_combined

,location,CanSino,Covaxin,Johnson&Johnson,Moderna,Novavax,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,Sinovac,Sputnik V,Country,Deaths/1M pop
0,Argentina,53950431.0,NaN,NaN,8.933868e+08,NaN,5.618581e+09,1.307661e+09,5.713239e+09,NaN,5.092133e+09,Argentina,2837.0
1,Austria,NaN,NaN,1.263894e+07,5.436887e+07,11819.0,7.372778e+07,4.557673e+08,NaN,NaN,NaN,Austria,2486.0
2,Belgium,NaN,NaN,1.621113e+07,9.354474e+07,107.0,1.256663e+08,5.989736e+08,NaN,NaN,NaN,Belgium,2946.0
3,Bulgaria,NaN,NaN,1.198064e+07,1.560478e+07,NaN,2.352012e+07,8.313276e+07,NaN,NaN,NaN,Bulgaria,5616.0
4,Chile,153505458.0,NaN,NaN,NaN,NaN,1.513017e+08,2.205676e+09,NaN,7.421275e+09,NaN,Chile,3350.0
5,Croatia,NaN,NaN,5.382836e+06,1.783213e+07,479.0,2.639237e+07,1.308606e+08,NaN,NaN,NaN,Croatia,4504.0
6,Cyprus,NaN,NaN,9.168150e+05,4.782633e+06,59.0,1.139933e+07,3.796457e+07,NaN,NaN,NaN,Cyprus,1115.0
7,Czechia,NaN,NaN,8.293091e+07,3.552392e+08,41996.0,2.252249e+08,3.441540e+09,NaN,NaN,NaN,Czechia,3987.0
8,Denmark,NaN,NaN,1.947563e+06,5.252257e+07,NaN,8.301687e+06,3.475988e+08,NaN,NaN,NaN,Denmark,1503.0
9,Ecuador,63941786.0,NaN,NaN,NaN,NaN,5.740528e+08,1.399258e+09,NaN,2.561852e+09,NaN,Ecuador,1990.0
10,Estonia,NaN,NaN,2.382223e+06,7.100996e+06,207.0,1.151180e+07,4.942954e+07,NaN,NaN,NaN,Estonia,2270.0
11,Finland,NaN,NaN,0.000000e+00,4.801806e+07,NaN,2.676701e+07,2.991248e+08,NaN,NaN,NaN,Finland,1816.0
12,France,NaN,NaN,2.978426e+08,4.074001e+09,NaN,2.579872e+09,2.522532e+10,NaN,NaN,NaN,France,2556.0
13,Germany,NaN,NaN,9.205289e+08,4.719170e+09,1348545.0,4.188139e+09,2.915364e+10,NaN,NaN,NaN,Germany,2078.0
14,Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,1.643527e+09,NaN,1.041142e+09,NaN,Hong Kong,1817.0
15,Hungary,NaN,NaN,9.331140e+06,3.786128e+07,NaN,5.847525e+07,3.139785e+08,1.045858e+08,NaN,6.708046e+07,Hungary,5088.0
16,Iceland,NaN,NaN,4.913000e+03,3.548400e+05,NaN,7.200000e+01,4.200838e+06,NaN,NaN,NaN,Iceland,663.0
17,Ireland,NaN,NaN,8.756933e+06,3.216439e+07,NaN,4.431227e+07,2.610461e+08,NaN,NaN,NaN,Ireland,1814.0
18,Italy,NaN,NaN,4.220771e+08,4.925954e+09,507902.0,2.425777e+09,2.053227e+10,NaN,NaN,NaN,Italy,3170.0
19,Japan,NaN,NaN,NaN,1.415208e+08,NaN,NaN,3.768902e+09,NaN,NaN,NaN,Japan,595.0
20,Latvia,NaN,NaN,5.726386e+07,1.244435e+08,2189.0,6.160848e+07,3.528115e+08,3.560000e+02,3.800000e+01,NaN,Latvia,3456.0
21,Liechtenstein,NaN,NaN,4.646000e+03,1.543114e+06,NaN,NaN,7.512990e+05,NaN,NaN,NaN,Liechtenstein,2449.0
22,Lithuania,NaN,NaN,8.440297e+06,1.224147e+07,NaN,2.402843e+07,1.097743e+08,NaN,NaN,NaN,Lithuania,3642.0
23,Luxembourg,NaN,NaN,1.596563e+06,5.942258e+06,532.0,4.841859e+06,2.516063e+07,NaN,NaN,NaN,Luxembourg,1918.0
24,Malta,NaN,NaN,1.202381e+06,4.502141e+06,NaN,1.063862e+07,2.624406e+07,NaN,NaN,NaN,Malta,1917.0
25,Nepal,NaN,NaN,1.118813e+08,1.812575e+08,NaN,3.530906e+08,1.984490e+07,6.771564e+08,NaN,NaN,Nepal,398.0
26,Netherlands,NaN,NaN,3.404599e+07,1.347043e+08,323.0,1.297025e+08,8.180842e+08,NaN,NaN,NaN,Netherlands,1336.0
27,Norway,NaN,NaN,2.614750e+05,6.222832e+07,NaN,8.044875e+06,2.860577e+08,NaN,NaN,NaN,Norway,1018.0
28,Peru,NaN,NaN,NaN,NaN,NaN,7.241190e+08,6.157883e+09,3.638123e+09,NaN,NaN,Peru,6569.0
29,Poland,NaN,NaN,8.837319e+07,1.480395e+08,11067.0,2.452178e+08,1.342429e+09,NaN,NaN,NaN,Poland,3170.0
30,Portugal,NaN,66.0,3.906225e+07,9.117436e+07,0.0,9.593523e+07,4.756099e+08,3.048300e+04,6.502200e+04,NaN,Portugal,2658.0
31,Romania,NaN,NaN,3.737618e+08,2.846886e+08,NaN,2.030900e+08,3.290245e+09,NaN,NaN,NaN,Romania,3586.0
32,Slovakia,NaN,NaN,4.577868e+06,2.406459e+07,660.0,2.319607e+07,1.717788e+08,NaN,NaN,3.805440e+05,Slovakia,3877.0
33,Slovenia,NaN,NaN,4.084514e+06,9.077059e+06,51.0,1.354594e+07,7.256522e+07,NaN,NaN,NaN,Slovenia,3417.0
34,South Africa,NaN,NaN,2.005567e+08,NaN,NaN,NaN,6.203154e+08,NaN,NaN,NaN,South Africa,1689.0
35,Spain,NaN,NaN,7.824416e+07,5.084171e+08,NaN,4.316192e+08,2.244537e+09,NaN,NaN,NaN,Spain,2606.0
36,Sweden,NaN,NaN,NaN,8.586669e+07,123.0,6.119736e+07,4.820933e+08,NaN,NaN,NaN,Sweden,2401.0
37,Switzerland,NaN,NaN,7.809174e+06,2.327226e+09,NaN,NaN,1.356914e+09,NaN,NaN,NaN,Switzerland,1647.0
38,Ukraine,NaN,NaN,3.987506e+06,4.637534e+08,NaN,7.451318e+08,1.810085e+09,NaN,1.334709e+09,NaN,Ukraine,2603.0
39,United States,NaN,NaN,4.872710e+09,5.529489e+10,NaN,NaN,7.977647e+10,NaN,NaN,NaN,United States,3494.0
40,Uruguay,NaN,NaN,NaN,NaN,NaN,2.724333e+07,5.897267e+08,NaN,1.047603e+09,NaN,Uruguay,2184.0

In [57]:
df_combined.fillna(0, inplace=True)

In [59]:
final_combined.fillna(0, inplace=True)
final_combined

,location,CanSino,Covaxin,Johnson&Johnson,Moderna,Novavax,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,Sinovac,Sputnik V,Country,Deaths/1M pop
0,Argentina,53950431.0,0.0,0.000000e+00,8.933868e+08,0.0,5.618581e+09,1.307661e+09,5.713239e+09,0.000000e+00,5.092133e+09,Argentina,2837.0
1,Austria,0.0,0.0,1.263894e+07,5.436887e+07,11819.0,7.372778e+07,4.557673e+08,0.000000e+00,0.000000e+00,0.000000e+00,Austria,2486.0
2,Belgium,0.0,0.0,1.621113e+07,9.354474e+07,107.0,1.256663e+08,5.989736e+08,0.000000e+00,0.000000e+00,0.000000e+00,Belgium,2946.0
3,Bulgaria,0.0,0.0,1.198064e+07,1.560478e+07,0.0,2.352012e+07,8.313276e+07,0.000000e+00,0.000000e+00,0.000000e+00,Bulgaria,5616.0
4,Chile,153505458.0,0.0,0.000000e+00,0.000000e+00,0.0,1.513017e+08,2.205676e+09,0.000000e+00,7.421275e+09,0.000000e+00,Chile,3350.0
5,Croatia,0.0,0.0,5.382836e+06,1.783213e+07,479.0,2.639237e+07,1.308606e+08,0.000000e+00,0.000000e+00,0.000000e+00,Croatia,4504.0
6,Cyprus,0.0,0.0,9.168150e+05,4.782633e+06,59.0,1.139933e+07,3.796457e+07,0.000000e+00,0.000000e+00,0.000000e+00,Cyprus,1115.0
7,Czechia,0.0,0.0,8.293091e+07,3.552392e+08,41996.0,2.252249e+08,3.441540e+09,0.000000e+00,0.000000e+00,0.000000e+00,Czechia,3987.0
8,Denmark,0.0,0.0,1.947563e+06,5.252257e+07,0.0,8.301687e+06,3.475988e+08,0.000000e+00,0.000000e+00,0.000000e+00,Denmark,1503.0
9,Ecuador,63941786.0,0.0,0.000000e+00,0.000000e+00,0.0,5.740528e+08,1.399258e+09,0.000000e+00,2.561852e+09,0.000000e+00,Ecuador,1990.0
10,Estonia,0.0,0.0,2.382223e+06,7.100996e+06,207.0,1.151180e+07,4.942954e+07,0.000000e+00,0.000000e+00,0.000000e+00,Estonia,2270.0
11,Finland,0.0,0.0,0.000000e+00,4.801806e+07,0.0,2.676701e+07,2.991248e+08,0.000000e+00,0.000000e+00,0.000000e+00,Finland,1816.0
12,France,0.0,0.0,2.978426e+08,4.074001e+09,0.0,2.579872e+09,2.522532e+10,0.000000e+00,0.000000e+00,0.000000e+00,France,2556.0
13,Germany,0.0,0.0,9.205289e+08,4.719170e+09,1348545.0,4.188139e+09,2.915364e+10,0.000000e+00,0.000000e+00,0.000000e+00,Germany,2078.0
14,Hong Kong,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,1.643527e+09,0.000000e+00,1.041142e+09,0.000000e+00,Hong Kong,1817.0
15,Hungary,0.0,0.0,9.331140e+06,3.786128e+07,0.0,5.847525e+07,3.139785e+08,1.045858e+08,0.000000e+00,6.708046e+07,Hungary,5088.0
16,Iceland,0.0,0.0,4.913000e+03,3.548400e+05,0.0,7.200000e+01,4.200838e+06,0.000000e+00,0.000000e+00,0.000000e+00,Iceland,663.0
17,Ireland,0.0,0.0,8.756933e+06,3.216439e+07,0.0,4.431227e+07,2.610461e+08,0.000000e+00,0.000000e+00,0.000000e+00,Ireland,1814.0
18,Italy,0.0,0.0,4.220771e+08,4.925954e+09,507902.0,2.425777e+09,2.053227e+10,0.000000e+00,0.000000e+00,0.000000e+00,Italy,3170.0
19,Japan,0.0,0.0,0.000000e+00,1.415208e+08,0.0,0.000000e+00,3.768902e+09,0.000000e+00,0.000000e+00,0.000000e+00,Japan,595.0
20,Latvia,0.0,0.0,5.726386e+07,1.244435e+08,2189.0,6.160848e+07,3.528115e+08,3.560000e+02,3.800000e+01,0.000000e+00,Latvia,3456.0
21,Liechtenstein,0.0,0.0,4.646000e+03,1.543114e+06,0.0,0.000000e+00,7.512990e+05,0.000000e+00,0.000000e+00,0.000000e+00,Liechtenstein,2449.0
22,Lithuania,0.0,0.0,8.440297e+06,1.224147e+07,0.0,2.402843e+07,1.097743e+08,0.000000e+00,0.000000e+00,0.000000e+00,Lithuania,3642.0
23,Luxembourg,0.0,0.0,1.596563e+06,5.942258e+06,532.0,4.841859e+06,2.516063e+07,0.000000e+00,0.000000e+00,0.000000e+00,Luxembourg,1918.0
24,Malta,0.0,0.0,1.202381e+06,4.502141e+06,0.0,1.063862e+07,2.624406e+07,0.000000e+00,0.000000e+00,0.000000e+00,Malta,1917.0
25,Nepal,0.0,0.0,1.118813e+08,1.812575e+08,0.0,3.530906e+08,1.984490e+07,6.771564e+08,0.000000e+00,0.000000e+00,Nepal,398.0
26,Netherlands,0.0,0.0,3.404599e+07,1.347043e+08,323.0,1.297025e+08,8.180842e+08,0.000000e+00,0.000000e+00,0.000000e+00,Netherlands,1336.0
27,Norway,0.0,0.0,2.614750e+05,6.222832e+07,0.0,8.044875e+06,2.860577e+08,0.000000e+00,0.000000e+00,0.000000e+00,Norway,1018.0
28,Peru,0.0,0.0,0.000000e+00,0.000000e+00,0.0,7.241190e+08,6.157883e+09,3.638123e+09,0.000000e+00,0.000000e+00,Peru,6569.0
29,Poland,0.0,0.0,8.837319e+07,1.480395e+08,11067.0,2.452178e+08,1.342429e+09,0.000000e+00,0.000000e+00,0.000000e+00,Poland,3170.0
30,Portugal,0.0,66.0,3.906225e+07,9.117436e+07,0.0,9.593523e+07,4.756099e+08,3.048300e+04,6.502200e+04,0.000000e+00,Portugal,2658.0
31,Romania,0.0,0.0,3.737618e+08,2.846886e+08,0.0,2.030900e+08,3.290245e+09,0.000000e+00,0.000000e+00,0.000000e+00,Romania,3586.0
32,Slovakia,0.0,0.0,4.577868e+06,2.406459e+07,660.0,2.319607e+07,1.717788e+08,0.000000e+00,0.000000e+00,3.805440e+05,Slovakia,3877.0
33,Slovenia,0.0,0.0,4.084514e+06,9.077059e+06,51.0,1.354594e+07,7.256522e+07,0.000000e+00,0.000000e+00,0.000000e+00,Slovenia,3417.0
34,South Africa,0.0,0.0,2.005567e+08,0.000000e+00,0.0,0.000000e+00,6.203154e+08,0.000000e+00,0.000000e+00,0.000000e+00,South Africa,1689.0
35,Spain,0.0,0.0,7.824416e+07,5.084171e+08,0.0,4.316192e+08,2.244537e+09,0.000000e+00,0.000000e+00,0.000000e+00,Spain,2606.0
36,Sweden,0.0,0.0,0.000000e+00,8.586669e+07,123.0,6.119736e+07,4.820933e+08,0.000000e+00,0.000000e+00,0.000000e+00,Sweden,2401.0
37,Switzerland,0.0,0.0,7.809174e+06,2.327226e+09,0.0,0.000000e+00,1.356914e+09,0.000000e+00,0.000000e+00,0.000000e+00,Switzerland,1647.0
38,Ukraine,0.0,0.0,3.987506e+06,4.637534e+08,0.0,7.451318e+08,1.810085e+09,0.000000e+00,1.334709e+09,0.000000e+00,Ukraine,2603.0
39,United States,0.0,0.0,4.872710e+09,5.529489e+10,0.0,0.000000e+00,7.977647e+10,0.000000e+00,0.000000e+00,0.000000e+00,United States,3494.0
40,Uruguay,0.0,0.0,0.000000e+00,0.000000e+00,0.0,2.724333e+07,5.897267e+08,0.000000e+00,1.047603e+09,0.000000e+00,Uruguay,2184.0

In [60]:
final_combined = final_combined.reset_index(drop = True)
final_combined.to_csv('Death_Rates.csv', index = False)

In [62]:
death_rates = final_combined[['location', 'Deaths/1M pop']]
death_rates.to_csv('death_rates.csv', index = False)
death_rates

         location  Deaths/1M pop
0       Argentina         2837.0
1         Austria         2486.0
2         Belgium         2946.0
3        Bulgaria         5616.0
4           Chile         3350.0
5         Croatia         4504.0
6          Cyprus         1115.0
7         Czechia         3987.0
8         Denmark         1503.0
9         Ecuador         1990.0
10        Estonia         2270.0
11        Finland         1816.0
12         France         2556.0
13        Germany         2078.0
14      Hong Kong         1817.0
15        Hungary         5088.0
16        Iceland          663.0
17        Ireland         1814.0
18          Italy         3170.0
19          Japan          595.0
20         Latvia         3456.0
21  Liechtenstein         2449.0
22      Lithuania         3642.0
23     Luxembourg         1918.0
24          Malta         1917.0
25          Nepal          398.0
26    Netherlands         1336.0
27         Norway         1018.0
28           Peru         6569.0
29         Poland         3170.0
30       Portugal         2658.0
31        Romania         3586.0
32       Slovakia         3877.0
33       Slovenia         3417.0
34   South Africa         1689.0
35          Spain         2606.0
36         Sweden         2401.0
37    Switzerland         1647.0
38        Ukraine         2603.0
39  United States         3494.0
40        Uruguay         2184.0

In [69]:
death_rates['Deaths/1M pop'].mean()

2639.9024390243903